"""create_rooms_table

Revision ID: 3fd3f7bc07d4
Revises: 
Create Date: 2025-11-30 18:38:24.921874

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fd3f7bc07d4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rooms',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.Text(), nullable=True),
    sa.Column('language', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rooms'))
    )
    op.create_index('ix_rooms_created_at', 'rooms', ['created_at'], unique=False)
    op.create_index('ix_rooms_language', 'rooms', ['language'], unique=False)
    op.create_index('ix_rooms_updated_at', 'rooms', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_rooms_updated_at', table_name='rooms')
    op.drop_index('ix_rooms_language', table_name='rooms')
    op.drop_index('ix_rooms_created_at', table_name='rooms')
    op.drop_table('rooms')
    # ### end Alembic commands ###

